"""Pitches table

Revision ID: 892030e811b9
Revises: 882158a44918
Create Date: 2020-07-17 19:26:02.922624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892030e811b9'
down_revision = '882158a44918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    # ### end Alembic commands ###
