"""Second migration

Revision ID: a86cd5fd27d7
Revises: b43432ee2708
Create Date: 2020-07-16 11:14:39.601126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a86cd5fd27d7'
down_revision = 'b43432ee2708'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pitches_category'), 'pitches', ['category'], unique=False)
    op.create_index(op.f('ix_pitches_description'), 'pitches', ['description'], unique=False)
    op.create_index(op.f('ix_pitches_title'), 'pitches', ['title'], unique=False)
    op.drop_column('roles', 'users')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.add_column('roles', sa.Column('users', sa.String(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pitches_title'), table_name='pitches')
    op.drop_index(op.f('ix_pitches_description'), table_name='pitches')
    op.drop_index(op.f('ix_pitches_category'), table_name='pitches')
    # ### end Alembic commands ###
